"""Scripted drift scenario — Phase 2 checkpoint deliverable.

Runs three cycles against an isolated mind/state directory:
  1. baseline cycle (boundary gets locked in)
  2. clean follow-up (no drift)
  3. drift-poisoned cycle (vocabulary + tool footprint shift; DEMOTE fires)

Writes a transcript markdown file describing what happened. Used by the
``chimera scenario drift`` CLI command and as the Phase 2 checkpoint
artifact.
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass
from pathlib import Path

from ..core import ChimeraLoop, CycleReport, LoopConfig
from ..core.mind import HeartbeatState, save_heartbeat
from ..drift import DriftConfig, DriftDetector
from ..memory import list_entities, list_transitions


@dataclass
class ScenarioResult:
    transcript_path: Path
    plan_demoted: bool
    final_plan_state: str | None
    plan_count: int


def _seed_mind(mind_dir: Path) -> None:
    mind_dir.mkdir(parents=True, exist_ok=True)
    (mind_dir / "INBOX.md").write_text(
        "# Inbox\n\n- [ ] scenario seed task\n", encoding="utf-8"
    )
    save_heartbeat(
        mind_dir / "HEARTBEAT.md",
        HeartbeatState(cycle=0, session_started_at="2026-05-18T22:00:00+00:00"),
        "",
    )


def _transcript(
    title: str,
    reports: list[CycleReport],
    plans: list,
    transitions: list,
) -> str:
    lines = [f"# {title}", ""]
    lines.append("_Generated by chimera.scenarios.drift_scenario._\n")
    lines.append("## Cycles\n")
    for r in reports:
        lines.append(f"### Cycle {r.cycle}")
        lines.append(f"- started: `{r.started_at}` completed: `{r.completed_at}`")
        lines.append(f"- tasks_seen: {r.tasks_seen}, flipped: {r.tasks_completed}")
        lines.append(f"- rotated: {r.rotated}, plan_demoted: {r.plan_demoted}")
        if r.drift_decision is not None:
            d = r.drift_decision
            lines.append(
                f"- drift decision: **{d.action.value}** — {d.reason}"
            )
            if d.nudge:
                lines.append(f"  - nudge: {d.nudge!r}")
        if r.pending_nudge:
            lines.append(f"- pending_nudge: {r.pending_nudge!r}")
        lines.append("")
        lines.append("Phase log:")
        for entry in r.phase_log:
            lines.append(f"  - {entry}")
        lines.append("")

    lines.append("## Plan entities (final state)\n")
    for p in plans:
        lines.append(
            f"- `{p.kfm_state}` `{p.name}` (id `{p.id[:8]}…`, entered@cycle {p.state_entered_at_cycle})"
        )
    lines.append("")

    lines.append("## Transitions\n")
    for t in transitions:
        lines.append(
            f"- cycle {t.cycle}: {t.from_state} → {t.to_state} by `{t.operator_type}` "
            f"({t.reason or 'no reason given'})"
        )
    lines.append("")

    lines.append("## Outcome\n")
    if any(r.plan_demoted for r in reports):
        lines.append(
            "✅ Drift detected and the current plan was demoted (K-Operator transition). "
            "A fresh STABLE plan was re-anchored so the loop can continue."
        )
    else:
        lines.append(
            "ℹ️ No drift was sufficient to demote the plan; behaviour stayed within thresholds."
        )
    return "\n".join(lines)


async def _arun(mind_dir: Path, state_dir: Path) -> ScenarioResult:
    _seed_mind(mind_dir)
    config = LoopConfig(mind_dir=mind_dir, state_dir=state_dir)

    # Aggressive thresholds so the scenario completes in three cycles.
    drift_config = DriftConfig(
        min_observations=1,
        assessment_interval=1,
        lockdown_threshold=0.10,
        warning_threshold=0.05,
    )
    detector = DriftDetector(
        state_path=state_dir / "drift" / "current.json",
        config=drift_config,
    )

    loop = ChimeraLoop(config, drift_detector=detector)
    reports: list[CycleReport] = []

    # 1: baseline cycle. Loop observes its own phase log; boundary marked at end.
    reports.append(await loop.run_one_cycle())

    # 2: clean follow-up cycle. Loop observes again. Composite should be low.
    reports.append(await loop.run_one_cycle())

    # 3: poison the detector with drastically different content, then run.
    for _ in range(10):
        detector.observe("zzz qqq xxx", tools=["foreign_tool"])
    reports.append(await loop.run_one_cycle())

    plans = list_entities(loop.db, kind="plan")
    all_transitions = []
    for p in plans:
        all_transitions.extend(list_transitions(loop.db, p.id))
    all_transitions.sort(key=lambda t: (t.cycle, t.id))

    transcript = _transcript(
        "Chimera — Phase 2 Drift Scenario Transcript",
        reports,
        plans,
        all_transitions,
    )
    transcript_path = mind_dir / "drift_scenario_transcript.md"
    transcript_path.write_text(transcript, encoding="utf-8")

    current = next((p for p in plans if p.name == "current"), None)
    loop.close()
    return ScenarioResult(
        transcript_path=transcript_path,
        plan_demoted=any(r.plan_demoted for r in reports),
        final_plan_state=current.kfm_state if current else None,
        plan_count=len(plans),
    )


def run_drift_scenario(mind_dir: Path, state_dir: Path) -> ScenarioResult:
    """Synchronous entry-point."""
    return asyncio.run(_arun(mind_dir, state_dir))
