"""Chimera memory: SQLite-backed ontology + activity log (ADR 0002 + ADR 0003)."""

from .graph import GRAPH_SCHEMA_VERSION, GraphQueryResult, GraphStore, default_graph_dir
from .federation_metrics import (
    FederationConnectivity,
    compute_connectivity,
    federation_metrics_enabled,
    from_trusted_rows,
)
from .entities import (
    EntityAlreadyExists,
    EntityError,
    EntityNotFound,
    EntityRecord,
    IllegalTransition,
    TransitionRecord,
    activity_window,
    create_entity,
    ensure_current_plan,
    get_entity,
    get_entity_by_name,
    list_entities,
    list_transitions,
    record_activity,
    record_api_call,
    record_ladder_outcome,
    transition_entity,
)
from .audit import (
    apply_approved_kills,
    audit_ontology,
    auto_archive_stale_deprecated,
    propose_kill_archived,
    reanchor_history,
)
from .engine_runs import (
    EngineRunRecord,
    engine_runs_summary,
    finish_engine_run,
    list_engine_runs,
    start_engine_run,
)
from .mutations import (
    Mutation,
    approve_mutation,
    bump_recurrence,
    create_mutation,
    get_mutation,
    list_mutations,
    mark_applied,
    mark_failed,
    queue_health,
    reject_mutation,
    sweep_stale,
)
from .store import (
    SQLITE_SCHEMA_VERSION,
    connect,
    default_db_path,
    init_schema,
    open_and_init,
    schema_version,
)

__all__ = [
    "EntityRecord",
    "TransitionRecord",
    "EntityError",
    "EntityNotFound",
    "EntityAlreadyExists",
    "IllegalTransition",
    "activity_window",
    "connect",
    "create_entity",
    "default_db_path",
    "ensure_current_plan",
    "get_entity",
    "get_entity_by_name",
    "init_schema",
    "list_entities",
    "list_transitions",
    "open_and_init",
    "record_activity",
    "record_api_call",
    "record_ladder_outcome",
    "transition_entity",
    "Mutation",
    "approve_mutation",
    "create_mutation",
    "get_mutation",
    "list_mutations",
    "mark_applied",
    "mark_failed",
    "reject_mutation",
    "sweep_stale",
    "apply_approved_kills",
    "audit_ontology",
    "auto_archive_stale_deprecated",
    "propose_kill_archived",
    "reanchor_history",
    "bump_recurrence",
    "queue_health",
    "EngineRunRecord",
    "engine_runs_summary",
    "finish_engine_run",
    "list_engine_runs",
    "start_engine_run",
    "GRAPH_SCHEMA_VERSION",
    "GraphQueryResult",
    "GraphStore",
    "default_graph_dir",
    "FederationConnectivity",
    "compute_connectivity",
    "federation_metrics_enabled",
    "from_trusted_rows",
    "SQLITE_SCHEMA_VERSION",
    "schema_version",
]
