"""Chimera memory: SQLite-backed ontology + activity log (ADR 0002 + ADR 0003)."""

from .graph import GRAPH_SCHEMA_VERSION, GraphQueryResult, GraphStore, default_graph_dir
from .entities import (
    EntityAlreadyExists,
    EntityError,
    EntityNotFound,
    EntityRecord,
    IllegalTransition,
    TransitionRecord,
    activity_window,
    create_entity,
    ensure_current_plan,
    get_entity,
    get_entity_by_name,
    list_entities,
    list_transitions,
    record_activity,
    record_api_call,
    record_ladder_outcome,
    transition_entity,
)
from .mutations import (
    Mutation,
    approve_mutation,
    create_mutation,
    get_mutation,
    list_mutations,
    mark_applied,
    mark_failed,
    reject_mutation,
    sweep_stale,
)
from .store import (
    SQLITE_SCHEMA_VERSION,
    connect,
    default_db_path,
    init_schema,
    open_and_init,
    schema_version,
)

__all__ = [
    "EntityRecord",
    "TransitionRecord",
    "EntityError",
    "EntityNotFound",
    "EntityAlreadyExists",
    "IllegalTransition",
    "activity_window",
    "connect",
    "create_entity",
    "default_db_path",
    "ensure_current_plan",
    "get_entity",
    "get_entity_by_name",
    "init_schema",
    "list_entities",
    "list_transitions",
    "open_and_init",
    "record_activity",
    "record_api_call",
    "record_ladder_outcome",
    "transition_entity",
    "Mutation",
    "approve_mutation",
    "create_mutation",
    "get_mutation",
    "list_mutations",
    "mark_applied",
    "mark_failed",
    "reject_mutation",
    "sweep_stale",
    "GRAPH_SCHEMA_VERSION",
    "GraphQueryResult",
    "GraphStore",
    "default_graph_dir",
    "SQLITE_SCHEMA_VERSION",
    "schema_version",
]
